<?php
/**
 * Phoenix Bank Prepayment module for Magento 2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Phoenix_BankPayment
 * @copyright  Copyright (c) 2017 Phoenix Media GmbH (http://www.phoenix-media.eu)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */


// @codingStandardsIgnoreFile
/**
 * @var $block \Phoenix\BankPayment\Block\Info
 */
?>
<dl class="payment-method phoenix_bankpayment">
    <dt class="title"><?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?> - <span style="font-style:italic;"><?php echo $block->escapeHtml(__('Account info')) ?></span></dt>
    <dd class="content">
        <?php $_accounts = $block->getAccounts(); ?>
        <?php foreach($_accounts as $_account): ?>
            <table class="bankpayment_info">
                <tbody>
                <?php if ($_accountHolder = $_account->getAccountHolder()): ?>
                    <tr>
                        <td class="bankcol1"><label><?php echo $block->escapeHtml(__('Account holder')) ?>:</label> </td>
                        <td class="bankcol2"><?php echo $block->escapeHtml($_accountHolder) ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_bankName = $_account->getBankName()): ?>
                    <tr>
                        <td class="bankcol1"><label><?php echo $block->escapeHtml(__('Bank name')) ?></label>: </td>
                        <td class="bankcol2"><?php echo $block->escapeHtml($_bankName) ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_iban = $_account->getIban()): ?>
                    <tr>
                        <td class="bankcol1"><label><?php echo $block->escapeHtml(__('IBAN')) ?>:</label> </td>
                        <td class="bankcol2"><?php echo $block->escapeHtml($_iban) ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_bic = $_account->getBic()): ?>
                    <tr>
                        <td class="bankcol1"><label><?php echo $block->escapeHtml(__('BIC')) ?>:</label> </td>
                        <td class="bankcol2"><?php echo $block->escapeHtml($_bic) ?></td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>
        <?php endforeach; ?>
        <?php if ($_customText = $block->escapeHtml($block->getMethod()->getCustomText())): ?>
            <br />
            <?php echo $_customText; ?><br />
        <?php endif; ?>
    </dd>
</dl>
